#!/usr/bin/with-contenv bash

# Make our folders
mkdir -p \
        /config/{custom,data,logs}

# copy config files
[[ ! -e /config/mosquitto.conf ]] && \
        cp /defaults/mosquitto.conf /config/mosquitto.conf

[[ ! -e /config/logs/mosquitto.log ]] && \
        touch /config/logs/mosquitto.log && \
        chmod 777 /config/logs/mosquitto.log

# permissions
chown -R abc:abc \
        /config

chmod 755 /etc
chmod 440 /etc/sudoers
